trigger:
 - no

pr:
  branches:
    exclude:
      - master

pool:
  vmImage: ubuntu-latest
      
steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
  displayName: 'npm install'

- script: |
    npm run build:docs:prod
  displayName: 'npm install and build'

